# Generated by Django 6.0 on 2026-01-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
