# Generated by Django 6.0 on 2026-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='assets/img/health/doctor-default.webp', upload_to='doctors/'),
        ),
    ]
